CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE posts(id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, content TEXT NOT NULL, author_id INTEGER, FOREIGN KEY(author_id) REFERENCES users(id));
CREATE TABLE comments (id INTEGER PRIMARY KEY AUTOINCREMENT, posts_id INTEGER NOT NULL, comment TEXT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTANP, FOREIGN KEY(posts_id) REFERENCES posts(id));
CREATE TABLE categories (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL UNIQUE
);
CREATE TABLE tags (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tag_name TEXT NOT NULL UNIQUE
);
CREATE TABLE post_tags (
post_id INTEGER,
tag_id INTEGER,
PRIMARY KEY (post_id, tag_id),
FOREIGN KEY(post_id) REFERENCES posts(id),
FOREIGN KEY(tag_id) REFERENCES tags(id)
);
